# Generated by Django 4.1 on 2022-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_cities_options_alter_provincies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email Verrified At',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
